/*
 * Book Blog API
 *
 * This is a blog about books.
 *
 * API version: 0.0.7
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Book struct {

	BookId int32 `json:"bookId"`

	BookName string `json:"bookName,omitempty"`

	Autor string `json:"autor,omitempty"`

	Info string `json:"info,omitempty"`
}
